language: python
python:
 - "2.6"
 - "2.7"

install:
 # bjoern needs to be compiled. dependencies:
 - sudo aptitude install libev-dev python-dev -y
 - pip install spec requests
 - python setup.py -q install

script: nosetests

notifications:
  email:
    recipients:
      - dr@nwebs.de
