#!/usr/bin/env python
# -*- coding: utf-8 -*-

from smart_grid_simulation.cli_parser import parse_actor_server_starter_arguments
from smart_grid_simulation.server import start_actor_server


if __name__ == '__main__':
    for host_port_tuple, actor in parse_actor_server_starter_arguments():
        start_actor_server(host_port_tuple, actor,
                           start_in_background_thread=True)

    try:
        print "I am done starting. Now wait."
        import time
        while True:
            time.sleep(60)
    except (KeyboardInterrupt, SystemExit):
        print "Exiting..."
